version: '3.7'
services:
    flask:
        build: containers/flask/.
        volumes:
            - ./flask_app:/var/www/app
        ports:
            - "5000:80"
        links:
            - db
            - mongo

    airflow:
        build: containers/airflow/.
        restart: always
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/plugins:/usr/local/airflow/plugins
            - ./airflow/scraped_files:/usr/local/airflow/scraped_files
        ports:
            - "8080:8080"
        links:
            - db
            - mongo

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: spanish-address
        ports:
            - "27011:27017"

    db:
        image: postgres:12.0-alpine
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./containers/postgres_data:/var/lib/postgresql/data/
        ports:
            - 5332:5432
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=address

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        links:
            - db
            - mongo